# Generated by Django 2.2 on 2021-06-18 01:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('soloProjectApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_likes',
            field=models.ManyToManyField(related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
