# Generated by Django 2.2 on 2021-06-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soloProjectApp', '0002_user_user_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='menuLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_likes', models.ManyToManyField(related_name='liked_posts', to='soloProjectApp.User')),
            ],
        ),
    ]
