# Generated by Django 2.2 on 2021-06-18 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soloProjectApp', '0003_menulike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_likes',
        ),
        migrations.DeleteModel(
            name='menuLike',
        ),
    ]
